/* abstractset.c generated by valac 0.56.3, the Vala compiler
 * generated from abstractset.vala, do not modify */

/* abstractset.vala
 *
 * Copyright (C) 2007  Jürg Billeter
 * Copyright (C) 2009  Didier Villevalois
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Julien Peeters <contact@julienpeeters.fr>
 */

#include "gee.h"
#include <glib-object.h>
#include <glib.h>

enum  {
	GEE_ABSTRACT_SET_0_PROPERTY,
	GEE_ABSTRACT_SET_G_TYPE,
	GEE_ABSTRACT_SET_G_DUP_FUNC,
	GEE_ABSTRACT_SET_G_DESTROY_FUNC,
	GEE_ABSTRACT_SET_READ_ONLY_VIEW_PROPERTY,
	GEE_ABSTRACT_SET_NUM_PROPERTIES
};
static GParamSpec* gee_abstract_set_properties[GEE_ABSTRACT_SET_NUM_PROPERTIES];

#define GEE_TYPE_READ_ONLY_COLLECTION (gee_read_only_collection_get_type ())
#define GEE_READ_ONLY_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEE_TYPE_READ_ONLY_COLLECTION, GeeReadOnlyCollection))
#define GEE_READ_ONLY_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEE_TYPE_READ_ONLY_COLLECTION, GeeReadOnlyCollectionClass))
#define GEE_IS_READ_ONLY_COLLECTION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEE_TYPE_READ_ONLY_COLLECTION))
#define GEE_IS_READ_ONLY_COLLECTION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEE_TYPE_READ_ONLY_COLLECTION))
#define GEE_READ_ONLY_COLLECTION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEE_TYPE_READ_ONLY_COLLECTION, GeeReadOnlyCollectionClass))

typedef struct _GeeReadOnlyCollection GeeReadOnlyCollection;
typedef struct _GeeReadOnlyCollectionClass GeeReadOnlyCollectionClass;

#define GEE_TYPE_READ_ONLY_SET (gee_read_only_set_get_type ())
#define GEE_READ_ONLY_SET(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GEE_TYPE_READ_ONLY_SET, GeeReadOnlySet))
#define GEE_READ_ONLY_SET_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GEE_TYPE_READ_ONLY_SET, GeeReadOnlySetClass))
#define GEE_IS_READ_ONLY_SET(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GEE_TYPE_READ_ONLY_SET))
#define GEE_IS_READ_ONLY_SET_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GEE_TYPE_READ_ONLY_SET))
#define GEE_READ_ONLY_SET_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GEE_TYPE_READ_ONLY_SET, GeeReadOnlySetClass))

typedef struct _GeeReadOnlySet GeeReadOnlySet;
typedef struct _GeeReadOnlySetClass GeeReadOnlySetClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _GeeAbstractSetPrivate {
	GType g_type;
	GBoxedCopyFunc g_dup_func;
	GDestroyNotify g_destroy_func;
	GWeakRef _read_only_view;
};

static gint GeeAbstractSet_private_offset;
static gpointer gee_abstract_set_parent_class = NULL;
static GeeSetIface * gee_abstract_set_gee_set_parent_iface = NULL;

 G_GNUC_INTERNAL void gee_abstract_set_reserved0 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved1 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved2 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved3 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved4 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved5 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved6 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved7 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved8 (GeeAbstractSet* self);
 G_GNUC_INTERNAL void gee_abstract_set_reserved9 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved0 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved1 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved2 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved3 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved4 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved5 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved6 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved7 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved8 (GeeAbstractSet* self);
static void gee_abstract_set_real_reserved9 (GeeAbstractSet* self);
 G_GNUC_INTERNAL GeeReadOnlySet* gee_read_only_set_new (GType g_type,
                                       GBoxedCopyFunc g_dup_func,
                                       GDestroyNotify g_destroy_func,
                                       GeeSet* set);
 G_GNUC_INTERNAL GeeReadOnlySet* gee_read_only_set_construct (GType object_type,
                                             GType g_type,
                                             GBoxedCopyFunc g_dup_func,
                                             GDestroyNotify g_destroy_func,
                                             GeeSet* set);
 G_GNUC_INTERNAL GType gee_read_only_collection_get_type (void) G_GNUC_CONST  G_GNUC_UNUSED ;
 G_GNUC_INTERNAL GType gee_read_only_set_get_type (void) G_GNUC_CONST  G_GNUC_UNUSED ;
static GObject * gee_abstract_set_constructor (GType type,
                                        guint n_construct_properties,
                                        GObjectConstructParam * construct_properties);
static void gee_abstract_set_finalize (GObject * obj);
static GType gee_abstract_set_get_type_once (void);
static void _vala_gee_abstract_set_get_property (GObject * object,
                                          guint property_id,
                                          GValue * value,
                                          GParamSpec * pspec);
static void _vala_gee_abstract_set_set_property (GObject * object,
                                          guint property_id,
                                          const GValue * value,
                                          GParamSpec * pspec);

static inline gpointer
gee_abstract_set_get_instance_private (GeeAbstractSet* self)
{
	return G_STRUCT_MEMBER_P (self, GeeAbstractSet_private_offset);
}

static void
gee_abstract_set_real_reserved0 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved0 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved0) {
		_klass_->reserved0 (self);
	}
}

static void
gee_abstract_set_real_reserved1 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved1 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved1) {
		_klass_->reserved1 (self);
	}
}

static void
gee_abstract_set_real_reserved2 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved2 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved2) {
		_klass_->reserved2 (self);
	}
}

static void
gee_abstract_set_real_reserved3 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved3 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved3) {
		_klass_->reserved3 (self);
	}
}

static void
gee_abstract_set_real_reserved4 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved4 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved4) {
		_klass_->reserved4 (self);
	}
}

static void
gee_abstract_set_real_reserved5 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved5 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved5) {
		_klass_->reserved5 (self);
	}
}

static void
gee_abstract_set_real_reserved6 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved6 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved6) {
		_klass_->reserved6 (self);
	}
}

static void
gee_abstract_set_real_reserved7 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved7 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved7) {
		_klass_->reserved7 (self);
	}
}

static void
gee_abstract_set_real_reserved8 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved8 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved8) {
		_klass_->reserved8 (self);
	}
}

static void
gee_abstract_set_real_reserved9 (GeeAbstractSet* self)
{
}

void
gee_abstract_set_reserved9 (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_if_fail (self != NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->reserved9) {
		_klass_->reserved9 (self);
	}
}

GeeAbstractSet*
gee_abstract_set_construct (GType object_type,
                            GType g_type,
                            GBoxedCopyFunc g_dup_func,
                            GDestroyNotify g_destroy_func)
{
	GeeAbstractSet * self = NULL;
	self = (GeeAbstractSet*) gee_abstract_collection_construct (object_type, g_type, (GBoxedCopyFunc) g_dup_func, (GDestroyNotify) g_destroy_func);
	self->priv->g_type = g_type;
	self->priv->g_dup_func = g_dup_func;
	self->priv->g_destroy_func = g_destroy_func;
	return self;
}

GeeSet*
gee_abstract_set_get_read_only_view (GeeAbstractSet* self)
{
	GeeAbstractSetClass* _klass_;
	g_return_val_if_fail (self != NULL, NULL);
	_klass_ = GEE_ABSTRACT_SET_GET_CLASS (self);
	if (_klass_->get_read_only_view) {
		return _klass_->get_read_only_view (self);
	}
	return NULL;
}

static GeeSet*
gee_abstract_set_real_get_read_only_view (GeeAbstractSet* base)
{
	GeeSet* result;
	GeeAbstractSet* self;
	GeeSet* instance = NULL;
	GObject* _tmp0_;
	GeeSet* _tmp1_;
	self = base;
	_tmp0_ = g_weak_ref_get (&self->priv->_read_only_view);
	instance = G_TYPE_CHECK_INSTANCE_CAST (_tmp0_, GEE_TYPE_SET, GeeSet);
	_tmp1_ = instance;
	if (_tmp1_ == NULL) {
		GeeReadOnlySet* _tmp2_;
		GeeSet* _tmp3_;
		_tmp2_ = gee_read_only_set_new (self->priv->g_type, (GBoxedCopyFunc) self->priv->g_dup_func, (GDestroyNotify) self->priv->g_destroy_func, (GeeSet*) self);
		_g_object_unref0 (instance);
		instance = (GeeSet*) _tmp2_;
		_tmp3_ = instance;
		g_weak_ref_set (&self->priv->_read_only_view, (GObject*) _tmp3_);
	}
	result = instance;
	return result;
}

static GObject *
gee_abstract_set_constructor (GType type,
                              guint n_construct_properties,
                              GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	GeeAbstractSet * self;
	parent_class = G_OBJECT_CLASS (gee_abstract_set_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GEE_TYPE_ABSTRACT_SET, GeeAbstractSet);
	g_weak_ref_clear (&self->priv->_read_only_view);
	g_weak_ref_init (&self->priv->_read_only_view, NULL);
	return obj;
}

static void
gee_abstract_set_class_init (GeeAbstractSetClass * klass,
                             gpointer klass_data)
{
	gee_abstract_set_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &GeeAbstractSet_private_offset);
	((GeeAbstractSetClass *) klass)->reserved0 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved0;
	((GeeAbstractSetClass *) klass)->reserved1 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved1;
	((GeeAbstractSetClass *) klass)->reserved2 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved2;
	((GeeAbstractSetClass *) klass)->reserved3 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved3;
	((GeeAbstractSetClass *) klass)->reserved4 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved4;
	((GeeAbstractSetClass *) klass)->reserved5 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved5;
	((GeeAbstractSetClass *) klass)->reserved6 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved6;
	((GeeAbstractSetClass *) klass)->reserved7 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved7;
	((GeeAbstractSetClass *) klass)->reserved8 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved8;
	((GeeAbstractSetClass *) klass)->reserved9 = (void (*) (GeeAbstractSet*)) gee_abstract_set_real_reserved9;
	GEE_ABSTRACT_SET_CLASS (klass)->get_read_only_view = gee_abstract_set_real_get_read_only_view;
	G_OBJECT_CLASS (klass)->get_property = _vala_gee_abstract_set_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_gee_abstract_set_set_property;
	G_OBJECT_CLASS (klass)->constructor = gee_abstract_set_constructor;
	G_OBJECT_CLASS (klass)->finalize = gee_abstract_set_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEE_ABSTRACT_SET_G_TYPE, g_param_spec_gtype ("g-type", "type", "type", G_TYPE_NONE, G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEE_ABSTRACT_SET_G_DUP_FUNC, g_param_spec_pointer ("g-dup-func", "dup func", "dup func", G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEE_ABSTRACT_SET_G_DESTROY_FUNC, g_param_spec_pointer ("g-destroy-func", "destroy func", "destroy func", G_PARAM_STATIC_STRINGS | G_PARAM_READWRITE | G_PARAM_CONSTRUCT_ONLY));
	/**
	 * {@inheritDoc}
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), GEE_ABSTRACT_SET_READ_ONLY_VIEW_PROPERTY, gee_abstract_set_properties[GEE_ABSTRACT_SET_READ_ONLY_VIEW_PROPERTY] = g_param_spec_object ("read-only-view", "read-only-view", "read-only-view", GEE_TYPE_SET, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static GType
gee_abstract_set_gee_set_get_g_type (GeeAbstractSet* self)
{
	return self->priv->g_type;
}

static GBoxedCopyFunc
gee_abstract_set_gee_set_get_g_dup_func (GeeAbstractSet* self)
{
	return self->priv->g_dup_func;
}

static GDestroyNotify
gee_abstract_set_gee_set_get_g_destroy_func (GeeAbstractSet* self)
{
	return self->priv->g_destroy_func;
}

static void
gee_abstract_set_gee_set_interface_init (GeeSetIface * iface,
                                         gpointer iface_data)
{
	gee_abstract_set_gee_set_parent_iface = g_type_interface_peek_parent (iface);
	iface->get_g_type = (GType (*) (GeeSet *)) gee_abstract_set_gee_set_get_g_type;
	iface->get_g_dup_func = (GBoxedCopyFunc (*) (GeeSet *)) gee_abstract_set_gee_set_get_g_dup_func;
	iface->get_g_destroy_func = (GDestroyNotify (*) (GeeSet *)) gee_abstract_set_gee_set_get_g_destroy_func;
	iface->get_read_only_view = (GeeSet* (*) (GeeSet *)) gee_abstract_set_get_read_only_view;
}

static void
gee_abstract_set_instance_init (GeeAbstractSet * self,
                                gpointer klass)
{
	self->priv = gee_abstract_set_get_instance_private (self);
}

static void
gee_abstract_set_finalize (GObject * obj)
{
	GeeAbstractSet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GEE_TYPE_ABSTRACT_SET, GeeAbstractSet);
	g_weak_ref_clear (&self->priv->_read_only_view);
	G_OBJECT_CLASS (gee_abstract_set_parent_class)->finalize (obj);
}

/**
 * Skeletal implementation of the {@link Set} interface.
 *
 * Contains common code shared by all set implementations.
 *
 * @see HashSet
 * @see TreeSet
 */
static GType
gee_abstract_set_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GeeAbstractSetClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gee_abstract_set_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GeeAbstractSet), 0, (GInstanceInitFunc) gee_abstract_set_instance_init, NULL };
	static const GInterfaceInfo gee_set_info = { (GInterfaceInitFunc) gee_abstract_set_gee_set_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType gee_abstract_set_type_id;
	gee_abstract_set_type_id = g_type_register_static (GEE_TYPE_ABSTRACT_COLLECTION, "GeeAbstractSet", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	g_type_add_interface_static (gee_abstract_set_type_id, GEE_TYPE_SET, &gee_set_info);
	GeeAbstractSet_private_offset = g_type_add_instance_private (gee_abstract_set_type_id, sizeof (GeeAbstractSetPrivate));
	return gee_abstract_set_type_id;
}

GType
gee_abstract_set_get_type (void)
{
	static volatile gsize gee_abstract_set_type_id__once = 0;
	if (g_once_init_enter (&gee_abstract_set_type_id__once)) {
		GType gee_abstract_set_type_id;
		gee_abstract_set_type_id = gee_abstract_set_get_type_once ();
		g_once_init_leave (&gee_abstract_set_type_id__once, gee_abstract_set_type_id);
	}
	return gee_abstract_set_type_id__once;
}

static void
_vala_gee_abstract_set_get_property (GObject * object,
                                     guint property_id,
                                     GValue * value,
                                     GParamSpec * pspec)
{
	GeeAbstractSet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GEE_TYPE_ABSTRACT_SET, GeeAbstractSet);
	switch (property_id) {
		case GEE_ABSTRACT_SET_READ_ONLY_VIEW_PROPERTY:
		g_value_take_object (value, gee_abstract_set_get_read_only_view (self));
		break;
		case GEE_ABSTRACT_SET_G_TYPE:
		g_value_set_gtype (value, self->priv->g_type);
		break;
		case GEE_ABSTRACT_SET_G_DUP_FUNC:
		g_value_set_pointer (value, self->priv->g_dup_func);
		break;
		case GEE_ABSTRACT_SET_G_DESTROY_FUNC:
		g_value_set_pointer (value, self->priv->g_destroy_func);
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_vala_gee_abstract_set_set_property (GObject * object,
                                     guint property_id,
                                     const GValue * value,
                                     GParamSpec * pspec)
{
	GeeAbstractSet * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, GEE_TYPE_ABSTRACT_SET, GeeAbstractSet);
	switch (property_id) {
		case GEE_ABSTRACT_SET_G_TYPE:
		self->priv->g_type = g_value_get_gtype (value);
		break;
		case GEE_ABSTRACT_SET_G_DUP_FUNC:
		self->priv->g_dup_func = g_value_get_pointer (value);
		break;
		case GEE_ABSTRACT_SET_G_DESTROY_FUNC:
		self->priv->g_destroy_func = g_value_get_pointer (value);
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

