/* bidirsortedmap.c generated by valac 0.56.3, the Vala compiler
 * generated from bidirsortedmap.vala, do not modify */

/* bidirsortedmap.vala
 *
 * Copyright (C) 2012  Maciej Piechotka
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Maciej Piechotka <uzytkownik2@gmail.com>
 */

#include "gee.h"
#include <glib-object.h>
#include <glib.h>

#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

static GType gee_bidir_sorted_map_get_type_once (void);

/**
 * Returns a bi-directional iterator for this map.
 *
 * @return a bi-directional map iterator
 */
GeeBidirMapIterator*
gee_bidir_sorted_map_bidir_map_iterator (GeeBidirSortedMap* self)
{
	GeeBidirSortedMapIface* _iface_;
	g_return_val_if_fail (self != NULL, NULL);
	_iface_ = GEE_BIDIR_SORTED_MAP_GET_INTERFACE (self);
	if (_iface_->bidir_map_iterator) {
		return _iface_->bidir_map_iterator (self);
	}
	return NULL;
}

/**
 * Returns an immutable empty sorted set.
 *
 * @return an immutable empty sorted set
 */
GeeBidirSortedMap*
gee_bidir_sorted_map_empty (GType k_type,
                            GBoxedCopyFunc k_dup_func,
                            GDestroyNotify k_destroy_func,
                            GType v_type,
                            GBoxedCopyFunc v_dup_func,
                            GDestroyNotify v_destroy_func)
{
	GeeTreeMap* _tmp0_;
	GeeTreeMap* _tmp1_;
	GeeBidirSortedMap* _tmp2_;
	GeeBidirSortedMap* _tmp3_;
	GeeBidirSortedMap* _tmp4_;
	GeeBidirSortedMap* result;
	_tmp0_ = gee_tree_map_new (k_type, (GBoxedCopyFunc) k_dup_func, (GDestroyNotify) k_destroy_func, v_type, (GBoxedCopyFunc) v_dup_func, (GDestroyNotify) v_destroy_func, NULL, NULL, NULL, NULL, NULL, NULL);
	_tmp1_ = _tmp0_;
	_tmp2_ = gee_abstract_bidir_sorted_map_get_read_only_view ((GeeAbstractBidirSortedMap*) _tmp1_);
	_tmp3_ = _tmp2_;
	_tmp4_ = _tmp3_;
	_g_object_unref0 (_tmp1_);
	result = _tmp4_;
	return result;
}

GeeBidirSortedMap*
gee_bidir_sorted_map_get_read_only_view (GeeBidirSortedMap* self)
{
	GeeBidirSortedMapIface* _iface_;
	g_return_val_if_fail (self != NULL, NULL);
	_iface_ = GEE_BIDIR_SORTED_MAP_GET_INTERFACE (self);
	if (_iface_->get_read_only_view) {
		return _iface_->get_read_only_view (self);
	}
	return NULL;
}

static void
gee_bidir_sorted_map_default_init (GeeBidirSortedMapIface * iface,
                                   gpointer iface_data)
{
	/**
	 * The read-only view of this set.
	 */
	g_object_interface_install_property (iface, g_param_spec_object ("read-only-view", "read-only-view", "read-only-view", GEE_TYPE_BIDIR_SORTED_MAP, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static GType
gee_bidir_sorted_map_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GeeBidirSortedMapIface), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gee_bidir_sorted_map_default_init, (GClassFinalizeFunc) NULL, NULL, 0, 0, (GInstanceInitFunc) NULL, NULL };
	GType gee_bidir_sorted_map_type_id;
	gee_bidir_sorted_map_type_id = g_type_register_static (G_TYPE_INTERFACE, "GeeBidirSortedMap", &g_define_type_info, 0);
	g_type_interface_add_prerequisite (gee_bidir_sorted_map_type_id, GEE_TYPE_SORTED_MAP);
	return gee_bidir_sorted_map_type_id;
}

GType
gee_bidir_sorted_map_get_type (void)
{
	static volatile gsize gee_bidir_sorted_map_type_id__once = 0;
	if (g_once_init_enter (&gee_bidir_sorted_map_type_id__once)) {
		GType gee_bidir_sorted_map_type_id;
		gee_bidir_sorted_map_type_id = gee_bidir_sorted_map_get_type_once ();
		g_once_init_leave (&gee_bidir_sorted_map_type_id__once, gee_bidir_sorted_map_type_id);
	}
	return gee_bidir_sorted_map_type_id__once;
}

